"""empty message

Revision ID: 9ca63297d2a7
Revises: 
Create Date: 2020-11-15 22:26:05.081177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ca63297d2a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('vote', sa.VARBINARY(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votes', 'vote')
    # ### end Alembic commands ###
